version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ~/repo/requirements.txt
      - run:
          name: Run script
          command: |
            . venv/bin/activate
            python3 paddle_booking.py

workflows:
  version: 2
  commit-and-scheduled:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "20 21 * * 5"
          filters:
            branches:
              only:
                - main
