version: 2.1

jobs:
  build:
    working_directory: ~/repo  # Change this line
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run script
          command: |
            . venv/bin/activate
            python3 paddle_booking.py

workflows:
  version: 2
  commit-and-scheduled:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "8 21 * * 5"
          filters:
            branches:
              only:
                - main
