name: Run Python Script

on:
  schedule:
    - cron: '45 21 * * 5' # Scheduled to run every Friday at 1:45 PM PST

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python3 paddle_booking.py
